### ISSUE TITLE
SQLancer GROUP BY HAVING cardinality test does not take duplicate values into account

### ISSUE THREAD

**Issue by robins** [sqlancer/sqlancer#1048]
SQLancer gives a false positive bug report. Here SQLancer misunderstands cardinality estimates, when values are repeated.

```
--java.lang.AssertionError: The size of the result sets mismatch (10 and 11)!
--First query: "SELECT t0.c0 FROM t0* GROUP BY t0.c1", whose cardinality is: 10
--Second query:"SELECT ALL t0.c0 FROM t0* GROUP BY t0.c1 HAVING t0.c0 UNION ALL SELECT ALL t0.c0 FROM t0 GROUP BY t0.c1 HAVING NOT (t0.c0) UNION ALL SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING (t0.c0) ISNULL", whose cardinality is: 11
```

```
test10=# SELECT t0.c0 FROM t0* GROUP BY t0.c1;
 c0
----






 f



(10 rows)

test10=# SELECT ALL t0.c0 FROM t0* GROUP BY t0.c1 HAVING t0.c0 UNION ALL SELECT ALL t0.c0 FROM t0 GROUP BY t0.c1 HAVING NOT (t0.c0) UNION ALL SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING (t0.c0) ISNULL;
 c0
----
 t
 f









(11 rows)
```

Looking at the table's contents, we see that 2 rows have the same value `$0.26'. When aggregated as above, it'd throw up only 1 row (since we're not asking for count of rows - just a value).

```
test10=# table t0;
 c0 |        c1
----+------------------
    | -$297,337,216.00
    |            $0.04
    |            $0.26
    |            $0.91
    |            $0.16
    |            $0.17
    |            $0.95
    |            $0.18
    |            $1.00
 f  |            $0.66
 t  |            $0.26
(11 rows)

test10=# SELECT t0.c0, count(*) FROM t0* GROUP BY t0.c1;
 c0 | count
----+-------
    |     1
    |     1
    |     1
    |     1
    |     1
    |     2
 f  |     1
    |     1
    |     1
    |     1
(10 rows)
```

**Comment by mrigger** [comment]
What test oracle are you using? Do you still have the statements for creating the database state, which would make debugging this more convenient?

**Comment by robins** [comment]
- TLP - Repro stack trace below. 
- Full file attached -  [db-1734222303.txt](https://github.com/user-attachments/files/18209083/db-1734222303.txt)


```
--java.lang.AssertionError: The size of the result sets mismatch (10 and 11)!
--First query: "SELECT t0.c0 FROM t0* GROUP BY t0.c1", whose cardinality is: 10
--Second query:"SELECT ALL t0.c0 FROM t0* GROUP BY t0.c1 HAVING t0.c0 UNION ALL SELECT ALL t0.c0 FROM t0 GROUP BY t0.c1 HAVING NOT (t0.c0) UNION ALL SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING (t0.c0) ISNULL", whose cardinality is: 11
--      at sqlancer.ComparatorHelper.assumeResultSetsAreEqual(ComparatorHelper.java:104)
--      at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.havingCheck(PostgresTLPHavingOracle.java:50)
--      at sqlancer.postgres.oracle.tlp.PostgresTLPHavingOracle.check(PostgresTLPHavingOracle.java:25)
--      at sqlancer.common.oracle.CompositeTestOracle.check(CompositeTestOracle.java:22)
--      at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--      at sqlancer.Main$DBMSExecutor.run(Main.java:454)
--      at sqlancer.Main$2.run(Main.java:668)
--      at sqlancer.Main$2.runThread(Main.java:650)
--      at sqlancer.Main$2.run(Main.java:641)
--      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
--      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
--      at java.base/java.lang.Thread.run(Thread.java:840)
---- Time: 2024/12/15 10:33:32
-- Database: db10
-- Database version: 16.6
-- seed value: 1734219403621
```

**Comment by robins** [comment]
Here is a simplified repro. 

It seems that this test is failing because of the documented Postgres caveat that `INHERITANCE` doesn't work well with PKs.

See this answer - https://stackoverflow.com/a/56637523/1378768


```
-- DROP DATABASE db10;
CREATE DATABASE db10 ;
\c db10
CREATE TABLE t0(c0 boolean , c1 money  PRIMARY KEY);
CREATE TABLE a() INHERITS(t0);
INSERT INTO a(c1, c0) VALUES(CAST(0.97673756 AS MONEY), TRUE);
INSERT INTO t0(c1) VALUES(0);
UPDATE t0 SET c1=0 ;

SELECT t0.c0 FROM t0* GROUP BY t0.c1;
-- result: 1 row

SELECT ALL t0.c0 FROM t0* GROUP BY t0.c1 HAVING t0.c0 
  UNION ALL 
SELECT ALL t0.c0 FROM t0 GROUP BY t0.c1 HAVING NOT (t0.c0) 
  UNION ALL 
SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING (t0.c0) ISNULL;
-- result: 2 rows

```
```
db10=# table t0;
 c0 |  c1
----+-------
    | $0.00
 t  | $0.00
(2 rows)

db10=# select * from only t0;
 c0 |  c1
----+-------
    | $0.00
(1 row)

db10=# table a;
 c0 |  c1
----+-------
 t  | $0.00
(1 row)

```

**Comment by mrigger** [comment]
That's strange. To me, this seems like a bug in PostgreSQL, but it seems that based on the response, this is actually intended.

I think the core issue is that PostgreSQL allows inheritance to ignore primary key constraints. If the primary key constraint is removed, we get an error "column "t0.c0" must appear in the GROUP BY clause or be used in an aggregate function" as the query is ambiguous. We don't get this error when using the query in the context of inheritance, though.

I think we might want to deal with this PostgreSQL quirk by disabling inheritance in testing, or what do you think?

**Comment by mrigger** [comment]
Further simplified:

```sql
CREATE TABLE t0(c0 boolean , c1 int primary key);
CREATE TABLE a() INHERITS(t0);
INSERT INTO a(c1, c0) VALUES(0, TRUE);
INSERT INTO a(c1, c0) VALUES(0, FALSE);

SELECT t0.c0 FROM t0 GROUP BY t0.c1;
-- result: true (1 row)

SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING t0.c0 
  UNION ALL 
SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING NOT (t0.c0) 
  UNION ALL 
SELECT t0.c0 FROM t0 GROUP BY t0.c1 HAVING (t0.c0) ISNULL;
-- result: true, false (2 rows)
```

**Comment by abdala-elgendy** [comment]
Is this issue solved or not yet?
