### ISSUE TITLE
Postgres: ERROR: time zone "false0.32726517016214185" not recognized

### ISSUE THREAD

**Issue by robins** [sqlancer/sqlancer#1049]
The random value generated for `TIMESTAMPTZ` doesn't conform with what the engine expects to see.

```
ERROR: time zone "false0.32726517016214185" not recognized
```

For e.g.
```
--java.lang.AssertionError: SELECT SUM(count) FROM (SELECT ALL ((abbrev('89.91.134.30') SIMILAR TO lower((('0.6734961381644076')||(-1001723539)))))::INT as count FROM ONLY t2, t0 INNER JOIN ONLY t1 ON (((((('87494780')||(FALSE)))||(0.32726517016214185)))::TIMESTAMPTZ) IS NOT NULL) as res;
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:124)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:154)
--	at sqlancer.common.oracle.NoRECOracle.extractCounts(NoRECOracle.java:151)
--	at sqlancer.common.oracle.NoRECOracle.check(NoRECOracle.java:87)
--	at sqlancer.postgres.oracle.PostgresNoRECOracle.check(PostgresNoRECOracle.java:42)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:456)
--	at sqlancer.Main$2.run(Main.java:670)
--	at sqlancer.Main$2.runThread(Main.java:652)
--	at sqlancer.Main$2.run(Main.java:643)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
--	at java.base/java.lang.Thread.run(Thread.java:840)
--Caused by: org.postgresql.util.PSQLException: ERROR: time zone "false0.32726517016214185" not recognized
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
--	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:144)
--	... 11 more
```

**Comment by mrigger** [comment]
I think it is conceptually difficult to fix this. Basically, we assume in PostgreSQL, but also in other implementations, that we can take a value of any type and cast it successfully to another type. For many data types, many such casts fail. We cannot easily fix this as the cast value can be the result of multiple other operations.
