### ISSUE TITLE
Postgres: Avoid specifying storage parameters for a partitioned table

### ISSUE THREAD

**Issue by robins** [sqlancer/sqlancer#1050]
Avoid specifying storage parameters for a partitioned table:

```
ERROR: cannot specify storage parameters for a partitioned table
```

```
--java.lang.AssertionError: CREATE UNLOGGED TABLE t4(c0 money , PRIMARY KEY(c0), CHECK(((pg_jit_available())OR((((0.1833738381431741)::VARCHAR(313))LIKE(replace('', 'CkW/C')))))), UNIQUE(c0), EXCLUDE (c0 text_ops NULLS FIRST WITH |)) PARTITION BY RANGE((length(left(-1489071351, '-1539790246')))circle_ops) WITH (autovacuum_freeze_min_age=407641664, autovacuum_vacuum_cost_limit=2799, autovacuum_vacuum_cost_delay=96, fillfactor=67, autovacuum_enabled=0, autovacuum_analyze_threshold=295434374, autovacuum_freeze_table_age=1280130573, autovacuum_vacuum_insert_scale_factor=0.2, parallel_workers=173, autovacuum_vacuum_threshold=1169352644, autovacuum_analyze_scale_factor=0.8);
--      at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:124)
--      at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:106)
--      at sqlancer.Main$QueryManager.execute(Main.java:360)
--      at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--      at sqlancer.postgres.PostgresProvider.createTables(PostgresProvider.java:306)
--      at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:197)
--      at sqlancer.postgres.PostgresProvider.generateDatabase(PostgresProvider.java:1)
--      at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--      at sqlancer.Main$DBMSExecutor.run(Main.java:459)
--      at sqlancer.Main$2.run(Main.java:673)
--      at sqlancer.Main$2.runThread(Main.java:655)
--      at sqlancer.Main$2.run(Main.java:646)
--      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
--      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
--      at java.base/java.lang.Thread.run(Thread.java:840)
--Caused by: org.postgresql.util.PSQLException: ERROR: cannot specify storage parameters for a partitioned table
--  Hint: Specify storage parameters for its leaf partitions instead.
--      at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--      at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--      at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--      at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
--      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
--      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
--      at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
--      at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
--      at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
--      at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:100)
--      ... 13 more
```

**Comment by robins** [comment]
Ideally this shouldn't happen after #956 .

I'll close this out for now - since I think I may have used an old binary whent his error came up - would reopen if this happens again with updated binaries.
