### ISSUE TITLE
Cannot parse "--use-constant-caching false" option

### ISSUE THREAD

**Issue by zhangysh1995** [sqlancer/sqlancer#234]
See the following:

````
root@39d4ee9ee7de:~/sqlancer/target# java -jar SQLancer-0.0.1-SNAPSHOT.jar --use-constant-caching false mysql   
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got false
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:788)
        at com.beust.jcommander.JCommander.parse(JCommander.java:356)
        at com.beust.jcommander.JCommander.parse(JCommander.java:335)
        at sqlancer.Main.executeMain(Main.java:424)
        at sqlancer.Main.main(Main.java:271)
````

Try another option should work:

````
root@39d4ee9ee7de:~/sqlancer/target# java -jar SQLancer-0.0.1-SNAPSHOT.jar --test-only-nonempty-tables false mysql 
[2020/10/12 10:05:18] Executed 7718 queries (1542 queries/s; 1.00/s dbs, successful statements: 99%). Threads shut down: 0.
[2020/10/12 10:05:23] Executed 24691 queries (3397 queries/s; 2.20/s dbs, successful statements: 99%). Threads shut down: 0.
````

**Comment by mrigger** [comment]
Thanks for the report! This should be fixed after merging https://github.com/sqlancer/sqlancer/pull/235.
