### ISSUE TITLE
Possible problem when testing with DuckDB

### ISSUE THREAD

**Issue by SteveLeungYL** [sqlancer/sqlancer#307]
When testing with DuckDB version 0.2.4 with SQLancer version 1.1.0, the correctness bug log doesn't seem right. And the generated queries might not be high quality. 

Sample command to run SQLancer: java -jar sqlancer-*.jar --num-threads 4 duckdb --oracle NoREC

The program generates 1~2 .log files every minute. And I didn't notice many "select" command here. Here is a sample .log file: 

```SQL
--java.lang.AssertionError: SELECT t0.c0, t0.rowid FROM t0 WHERE (DATE '1970-01-17' NOT BETWEEN t0.c0 AND t0.c0); -- 1
--SELECT SUM(count) FROM (SELECT (((DATE '1970-01-17' NOT BETWEEN t0.c0 AND t0.c0) IS NOT NULL AND (DATE '1970-01-17' NOT BETWEEN t0.c0 AND t0.c0)) ::INT8)as count FROM t0) as res -- 0
--	at sqlancer.duckdb.test.DuckDBNoRECOracle.check(DuckDBNoRECOracle.java:63)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:49)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:323)
--	at sqlancer.Main$2.run(Main.java:507)
--	at sqlancer.Main$2.runThread(Main.java:485)
--	at sqlancer.Main$2.run(Main.java:475)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:834)
---- Time: 2021/02/06 15:46:01
-- Database: database6
-- Database version: v0.2.4
-- seed value: 1612644047074
CREATE TABLE t0(c0 DATE);
CREATE TABLE t24(c0 FLOAT4);
UPDATE t0 SET rowid=362102307, c0=0.35596816344204085;
UPDATE t24 SET c0=true;
INSERT INTO t0(c0, rowid) VALUES ('y!2w}Ds', DATE '1970-01-02'), ('', false);
INSERT INTO t0(rowid, c0) VALUES (true, TIMESTAMP '1970-01-12 21:19:26'), (true, true);
INSERT INTO t0(rowid) VALUES (-1125900367);
INSERT INTO t24(c0, rowid) VALUES (1107062174, false), ('*', -1291054279);
INSERT INTO t0(rowid, c0) VALUES (-139610940, 1649851194), (1410126715, DATE '1970-01-01'), (DEFAULT, DATE '1970-01-04'), (TIMESTAMP '1969-12-11 11:21:54', TIMESTAMP '1970-01-22 17:12:19');
INSERT INTO t0(c0) VALUES (''), (-1405600525);
INSERT INTO t0(c0) VALUES ('텬');
INSERT INTO t0(c0) VALUES (2050146557), (DATE '1970-01-05');
INSERT INTO t24(rowid) VALUES (false), ('GQCJye'), (1018811748);
INSERT INTO t24(c0) VALUES (0.1529856435394059), (0.8213028273116049);
VACUUM;
CREATE UNIQUE INDEX i3 ON t0(rowid , c0 ) WHERE ((((t0.c0)NOT SIMILAR TO(((false)NOT SIMILAR TO(t0.c0))))) ::BOOL);
CREATE UNIQUE INDEX i3 ON t24(rowid , c0 );
CREATE UNIQUE INDEX i1 ON t0(c0 , rowid ) WHERE (((862235419)%(0.638365711942165)) IN ((DATE '1969-12-28' BETWEEN 0.8509310043293881 AND t0.c0), (((CASE 220432677 WHEN 0.9394938783225824 THEN t0.c0 WHEN TIMESTAMP '1969-12-07 13:23:17' THEN '1146972713' ELSE 'W' END )) IS NOT NULL)));
CREATE INDEX i0 ON t0(c0 , rowid ) WHERE 0.2500536364154836;
CREATE INDEX i0 ON t0(rowid , c0 ) WHERE t0.c0;
CREATE UNIQUE INDEX i0 ON t0(c0 , rowid );
CREATE INDEX i2 ON t0(c0 , rowid );
CREATE INDEX i1 ON t24(rowid );
CREATE UNIQUE INDEX i1 ON t0(c0 DESC, rowid );
CREATE UNIQUE INDEX i2 ON t0(c0 , rowid ) WHERE t0.rowid;
CREATE UNIQUE INDEX i1 ON t24(rowid , c0 );
CREATE UNIQUE INDEX i4 ON t0(c0 );
INSERT INTO t24(rowid, c0) VALUES ('', -64363592), ('530799421', DATE '1969-12-07');
INSERT INTO t24(c0, rowid) VALUES (-1358067643, false), (NULL, DATE '1970-01-22');
INSERT INTO t0(rowid) VALUES (false);
INSERT INTO t0(c0, rowid) VALUES (TIMESTAMP '1969-12-14 04:27:27', true);
INSERT INTO t24(rowid, c0) VALUES (DEFAULT, 537912925), (145832631, TIMESTAMP '1970-01-25 10:06:34'), (0.19426469992258943, '1107062174');
INSERT INTO t24(rowid) VALUES (0.4324203111760482), (-1626339408);
INSERT INTO t24(c0) VALUES (DATE '1970-01-13');
INSERT INTO t0(c0, rowid) VALUES (false, 1095573456);
INSERT INTO t24(c0) VALUES (''), (394257718), (DATE '1969-12-22');
INSERT INTO t24(c0) VALUES (TIMESTAMP '1970-01-13 23:41:09');
INSERT INTO t0(c0) VALUES (DEFAULT);
CREATE UNIQUE INDEX i3 ON t0(rowid , c0 ) WHERE ((t0.c0)-(((((t0.c0)<=(DATE '1969-12-27'))) IS NULL)));
CREATE UNIQUE INDEX i3 ON t24(c0 );
CREATE INDEX i4 ON t24(rowid , c0 ) WHERE (((((t24.rowid)%(t24.c0))) COLLATE POSIX) NOT BETWEEN TIMESTAMP '1969-12-31 15:09:21' AND ((((t24.rowid) COLLATE NOCASE))%(-985611768)));
CREATE UNIQUE INDEX i2 ON t0(rowid ) WHERE (+ TIMESTAMP '1969-12-11 00:27:43');
CREATE INDEX i0 ON t0(c0 ) WHERE false;
UPDATE t0 SET rowid='0.6543913055094072';
UPDATE t24 SET c0=1.234550447E9;
UPDATE t0 SET rowid='ᕚ^', c0=TIMESTAMP '1970-01-13 20:55:48';
UPDATE t0 SET c0=DATE '1969-12-31', rowid='';
UPDATE t0 SET c0=-1423491342;
UPDATE t0 SET c0=-3.79107417E8, rowid=NULL;
UPDATE t24 SET c0=0.6896978459983308, rowid='0.055203534343885474';
UPDATE t24 SET c0=719430052, rowid='1877100916';
UPDATE t24 SET c0=TIMESTAMP '1969-12-19 01:31:10', rowid=TIMESTAMP '1970-01-24 03:11:42';
UPDATE t0 SET rowid=0.524248548633458, c0=1085904182;
UPDATE t0 SET rowid='', c0='7(';
UPDATE t24 SET rowid=0.6086304452143656;
UPDATE t24 SET rowid=-2041737147, c0=0.6960086820739578;
UPDATE t0 SET c0=-1320543153, rowid=2008541285;
UPDATE t24 SET rowid='ysW <', c0=true;
UPDATE t0 SET rowid=219326964;
UPDATE t0 SET rowid=670603744;
UPDATE t24 SET c0=DATE '1969-12-25', rowid=0.32557530049312067;
UPDATE t0 SET rowid=1596416693;
UPDATE t24 SET c0=52327443, rowid=TIMESTAMP '1970-01-21 19:22:00';
UPDATE t24 SET c0=1180505456, rowid=0.3508644984165019;
UPDATE t0 SET rowid=DATE '1969-12-30', c0=0.2855337379548075;
UPDATE t24 SET c0=0.47423139167199846;
UPDATE t0 SET c0=TIMESTAMP '1970-01-09 21:59:47';
UPDATE t24 SET c0=0.4381612733396911;
UPDATE t0 SET c0='-1971820014', rowid=TIMESTAMP '1970-01-09 03:58:09';
UPDATE t0 SET c0='F,)N', rowid=1.410630346E9;
UPDATE t24 SET c0=0.05663310856488435, rowid='-Inf';
UPDATE t24 SET c0=-853215649;
UPDATE t0 SET rowid=TIMESTAMP '1970-01-06 22:26:39';
UPDATE t0 SET rowid=false;
UPDATE t0 SET rowid=true;
UPDATE t0 SET c0=TIMESTAMP '1970-01-25 07:52:20', rowid=((DATE '1969-12-31')>=(((-1414278111) ::BOOL)));
UPDATE t24 SET c0=true, rowid=DATE '1970-01-19';
UPDATE t24 SET rowid=false;
UPDATE t0 SET rowid=false, c0=0.423883120827818;
UPDATE t0 SET c0=false;
UPDATE t0 SET c0=TIMESTAMP '1970-01-22 20:35:38', rowid=0.9750461127805642;
UPDATE t0 SET c0='', rowid='-667157092';
UPDATE t0 SET c0='m乗a^vd';
UPDATE t0 SET c0=DATE '1970-01-13';
CREATE UNIQUE INDEX i0 ON t24(rowid , c0 ) WHERE NULL;
CREATE INDEX i1 ON t0(rowid );
CREATE UNIQUE INDEX i1 ON t24(c0 , rowid ) WHERE (t24.rowid LIKE TIMESTAMP '1969-12-08 20:24:48' ESCAPE TIMESTAMP '1970-01-01 11:21:39');
CREATE INDEX i3 ON t24(c0 ASC);
CREATE UNIQUE INDEX i2 ON t24(c0 );
INSERT INTO t24(c0) VALUES (0.6560029135109771);
```

When testing these generated queries directly in DuckDB, I notice the results are full of "Error: Binder Error: Cannot create an index on the rowid!" and "Error: Catalog Error: Column with name rowid does not exist!" 

Am I configuring the program wrong?

**Comment by mrigger** [comment]
Thank you for the report! I still need to look at this in detail, but here are some clarifications/comments:

> correctness bug log doesn't seem right

A `*.log` file is only generated when SQLancer identifies a bug in the DBMS under test. It could be that the DuckDB implementation changed in a way so that the NoREC oracle currently does not work - I will check.

> And the generated queries might not be high quality.

SQLancer uses naive random database and query generation, so this is expected.

> And I didn't notice many "select" command here.

The select statements for a generated database are logged in the `*-cur.log` files. You can control the number using the `--num-queries` option.

> When testing these generated queries directly in DuckDB, I notice the results are full of "Error: Binder Error: Cannot create an index on the rowid!" and "Error: Catalog Error: Column with name rowid does not exist!"

It is expected that some statements result in run-time errors. While SQLancer generally aims to generate both syntactically and semantically correct queries, this is often tricky to achieve in practice. Each statement typically has a list of "expected errors" associated with it, which are ignored by SQLancer.

Hope this already helps!
