### ISSUE TITLE
Options don't work

### ISSUE THREAD

**Issue by jumarbach** [sqlancer/sqlancer#31]
Hi Manuel,
A couple of options, num-threads, num-tries, max-expression-depthand  and num-queries don't work right now. I've tried both --num_threads and --num-threads, but get the same exception in both cases:

`Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--num-threads' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:796)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at sqlancer.Main.executeMain(Main.java:296)
	at sqlancer.Main.main(Main.java:273)
`

**Comment by mrigger** [comment]
Thanks a lot for the bug report! I've made the naming of the options consistent earlier today, see #30. Now, all options use a dash, rather than an underscore. I'm very sorry that these changes affected you negatively.

For me, the following works:

```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --num-threads 4 --num-tries 3 --num-queries 3 sqlite3 --oracle NoREC
[2020/06/09 18:59:59] Executed 2280 queries (455 queries/s; 167.70/s dbs, successful statements: 92%). Threads shut down: 0.
```
Is it possible that you specified `--num-threads` after the DBMS that you want to test? If yes, this is expected. Currently, options that are not specific to a DBMS-testing implementation need to go before the name of the DBMS that should be tested. This means that the following works:
```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar --num-threads 4 sqlite3
```
This results in an error:
```
$ java -jar SQLancer-0.0.1-SNAPSHOT.jar sqlite3 --num-threads 4
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '--num-threads' but no main parameter was defined in your arg class
	at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:954)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:755)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parseValues(JCommander.java:796)
	at com.beust.jcommander.JCommander.parse(JCommander.java:356)
	at com.beust.jcommander.JCommander.parse(JCommander.java:335)
	at sqlancer.Main.executeMain(Main.java:296)
	at sqlancer.Main.main(Main.java:273)
```
If this wasn't the culprit, I would suggest to use `mvn clean package` to rebuild SQLancer. Please let me know if this works.
