### ISSUE TITLE
TiDB unsupported datetime issue

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#669]
See https://github.com/sqlancer/sqlancer/actions/runs/3730173900/jobs/6326916418:

```sql
--java.lang.AssertionError: datetime(6)
--	at sqlancer.tidb.TiDBSchema.getColumnType(TiDBSchema.java:[273](https://github.com/sqlancer/sqlancer/actions/runs/3730173900/jobs/6326916418#step:7:274))
--	at sqlancer.tidb.TiDBSchema.getTableColumns(TiDBSchema.java:346)
--	at sqlancer.tidb.TiDBSchema.fromConnection(TiDBSchema.java:295)
--	at sqlancer.tidb.TiDBProvider$TiDBGlobalState.readSchema(TiDBProvider.java:75)
--	at sqlancer.tidb.TiDBProvider$TiDBGlobalState.readSchema(TiDBProvider.java:1)
--	at sqlancer.GlobalState.updateSchema(GlobalState.java:145)
--	at sqlancer.SQLGlobalState.executeEpilogue(SQLGlobalState.java:27)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:109)
--	at sqlancer.StatementExecutor.executeStatements(StatementExecutor.java:70)
--	at sqlancer.tidb.TiDBProvider.generateDatabase(TiDBProvider.java:126)
--	at sqlancer.tidb.TiDBProvider.generateDatabase(TiDBProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: 2022/12/19 09:40:13
-- Database: database8
-- Database version: 5.7.25-TiDB-v6.1.3
-- seed value: 8
USE test;
DROP DATABASE IF EXISTS database8;
CREATE DATABASE database8;
USE database8;
CREATE TABLE t0(c0 DOUBLE UNSIGNED ZEROFILL );
DELETE FROM t0 WHERE CAST(t0.c0 AS UNSIGNED) ORDER BY -2095437996 DESC;
ANALYZE TABLE t0 WITH 512 BUCKETS;
UPDATE t0 SET c0='6' WHERE ((((-1179736678)!=((+ (t0.c0)))))<=>(-1339690757));
UPDATE t0 SET c0=t0.c0;
ADMIN CHECKSUM TABLE t0;
CREATE OR REPLACE VIEW v0(c0, c1, c2) AS SELECT COALESCE(CAST(((((t0.c0) IS NULL))>>((BINARY ('	')))) AS DATE)), NULL, t0.c0 FROM t0 GROUP BY DEFAULT(t0.c0) HAVING t0.c0 ORDER BY ((t0.c0)AND(-2.095437996E9)) DESC;
```

**Comment by mrigger** [comment]
@hawkingrei, perhaps you could have a look when you have time?

**Comment by hawkingrei** [comment]
> @hawkingrei, perhaps you could have a look when you have time?

Let me take a look.

**Comment by mrigger** [comment]
Thanks a lot!

**Comment by mrigger** [comment]
The issue still persists, here is another example:
```
--java.lang.AssertionError: double(8,6)
--	at sqlancer.tidb.TiDBSchema.getColumnType(TiDBSchema.java:280)
--	at sqlancer.tidb.TiDBSchema.getTableColumns(TiDBSchema.java:354)
--	at sqlancer.tidb.TiDBSchema.fromConnection(TiDBSchema.java:302)
--	at sqlancer.tidb.TiDBProvider$TiDBGlobalState.readSchema(TiDBProvider.java:75)
--	at sqlancer.tidb.TiDBProvider$TiDBGlobalState.readSchema(TiDBProvider.java:1)
--	at sqlancer.GlobalState.updateSchema(GlobalState.java:145)
--	at sqlancer.SQLGlobalState.executeEpilogue(SQLGlobalState.java:27)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:109)
--	at sqlancer.StatementExecutor.executeStatements(StatementExecutor.java:70)
--	at sqlancer.tidb.TiDBProvider.generateDatabase(TiDBProvider.java:126)
--	at sqlancer.tidb.TiDBProvider.generateDatabase(TiDBProvider.java:1)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:52)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--
-- Time: 2023/01/29 05:31:21
-- Database: database4
-- Database version: 5.7.25-TiDB-v6.5.0
-- seed value: 4
USE test;
DROP DATABASE IF EXISTS database4;
CREATE DATABASE database4;
USE database4;
CREATE TABLE t0(c0 BOOL UNSIGNED DEFAULT false , PRIMARY KEY(c0));
CREATE OR REPLACE ALGORITHM=UNDEFINED VIEW v0(c0, c1, c2, c3, c4) AS SELECT t0.c0, PI(), t0.c0, FORMAT(-550318[283](https://github.com/sqlancer/sqlancer/actions/runs/4035273876/jobs/6937078631#step:7:284), ((t0.c0) IS NULL)), NULL FROM t0;
```
