### ISSUE TITLE
failed to connect to a postgresql 

### ISSUE THREAD

**Issue by mozz85** [sqlancer/sqlancer#677]
### startup command
```
java -jar sqlancer-2.0.0.jar --username xxxxxxxx --password xxxxxxxx  --host xxxxxxxx --port 5432 postgres --connection-url postgresql://xxxxxxxx:5432/sqlancer --oracle NoREC
```
### Didn't connect to the database which i demanded. Instead it tries to connect the defaut test database
```
SQLancer failed creating a test database, indicating that SQLancer might have failed connecting to the DBMS. In order to change the username, password, host and port, you can use the --username, --password, --host and --port options.


org.postgresql.util.PSQLException: FATAL: database "test" does not exist

```

**Comment by mozz85** [comment]
### The call stack
```
org.postgresql.util.PSQLException: FATAL: database "test" does not exist
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.readStartupMessages(QueryExecutorImpl.java:2788)
        at org.postgresql.core.v3.QueryExecutorImpl.<init>(QueryExecutorImpl.java:174)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:290)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
        at org.postgresql.Driver.makeConnection(Driver.java:434)
        at org.postgresql.Driver.connect(Driver.java:291)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:268)
        at sqlancer.postgres.PostgresProvider.createDatabase(PostgresProvider.java:1)
        at sqlancer.Main$DBMSExecutor.testConnection(Main.java:332)
        at sqlancer.Main.executeMain(Main.java:509)
        at sqlancer.Main.main(Main.java:296)
```

**Comment by mrigger** [comment]
Thanks for posting the issue! I think you need to create a database called `test` (see https://www.postgresql.org/docs/current/sql-createdatabase.html), which SQLancer uses for connecting.

**Comment by mozz85** [comment]
thanks for your reply. It does help.
However it would be better if there are some description about this in --help output，i think。

**Comment by mrigger** [comment]
Thanks for the suggestion! For now, we have created a FAQ entry at https://github.com/sqlancer/sqlancer/blob/master/README.md#when-starting-sqlancer-i-get-an-error-such-as-database-test-does-not-exist-how-can-i-run-sqlancer-without-this-error.
