### ISSUE TITLE
The generated sql statements have error for postgresql 14.6 . 

### ISSUE THREAD

**Issue by mozz85** [sqlancer/sqlancer#684]
## generated sql statements
```
CREATE TEMPORARY TABLE IF NOT EXISTS t0(c0 DECIMAL ) WITH (autovacuum_analyze_scale_factor=0.01, parallel_workers=879, fillfactor=70, autovacuum_vacuum_cost_limit=7601);

CREATE TABLE IF NOT EXISTS t1(c0 inet ) INHERITS(t0) PARTITION BY HASH((((chr((FALSE)::INT))||(CAST(0.2578964 AS MONEY))))) WITH (autovacuum_analyze_scale_factor=0.9, parallel_workers=73, autovacuum_analyze_threshold=1070764457, autovacuum_vacuum_cost_delay=36, autovacuum_freeze_min_age=86298167, autovacuum_freeze_table_age=279810749);
```
## the error i get when it's executed in navicat
```
> ERROR:  cannot create partitioned table as inheritance child
```

## reference
```
Notably, a partition cannot have any parents other than the partitioned table it is a partition of, nor can a table inherit from both a partitioned table and a regular table. That means partitioned tables and their partitions never share an inheritance hierarchy with regular tables.

https://www.postgresql.org/docs/14/ddl-partitioning.html
```

**Comment by mrigger** [comment]
Thanks for reporting this! The SQLancer implementation is not up-to-date and works for Postgres version 12: https://github.com/sqlancer/sqlancer/blob/7f1efbd4ba672f387ea2034b07bcbaf3b23e69d2/.github/workflows/main.yml#L266

In this specific case, SQLancer already seems to declare this error as an expected error for the currently supported Postgres version: https://github.com/sqlancer/sqlancer/blob/7f1efbd4ba672f387ea2034b07bcbaf3b23e69d2/src/sqlancer/postgres/gen/PostgresTableGenerator.java#L45

I assume your expectation is that SQLancer produces only valid SQL statements? While statements generated by SQLancer are expected to be syntactically valid, they might have semantic errors, such as the one you posted above, because it is difficult to avoid generating them.

**Comment by mozz85** [comment]
Thanks for replying! 
I am trying to reproduce the logic bug (sqlancer found in NoREC way) which documented in *.log file.
The log file, seems to me,  contains two part. The first is the sql statement triggered assertion error. and the second is made of sql statements which set up the enviroment.
**Now i got 2 questions.**
1. How can i tell the difference between the execution result of optimized select statement and the non-optimized one, if there's only one select statement logged, like here 'SELECT SUM(count) FROM (SELECT CAST(((t1.c0)>= ...... as res;'?
2. Can i still set up the logic bug environment by  ignoring the sql statement which has semantic errors or should i just move on to another *.log file? 
```
--java.lang.AssertionError: SELECT SUM(count) FROM (SELECT CAST(((t1.c0)>=(0.36096321309545353894776553715928457677364349365234375)) AS INT) as count FROM t1* INNER JOIN ONLY t3 ON (((((((('(-1615551165,2000798136]'::int4range)+('[-85071363,1466807588)'::int4range)))-((('(-206172409,1164549933]'::int4range)*('[-509639586,-242999266]'::int4range)))))+((((('(-1722088893,978828203)'::int4range)+('[-1955778868,-1341972803)'::int4range)))-((('[-1471880238,-1050392773)'::int4range)*('[-135465764,1837920325)'::int4range)))))))>>((((((('[978828203,1479848151]'::int4range)-('[-1361614762,-1130673932]'::int4range)))-((('(-989372586,-838928569]'::int4range)*('[-1448572344,589973085)'::int4range)))))+((((('[-2142313481,-973476715)'::int4range)*('(-1649923344,1073932051]'::int4range)))*((('(-539871742,-244024557)'::int4range)*('(-1421903006,-1380396300]'::int4range))))))))) as res;
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:109)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:139)
--	at sqlancer.postgres.oracle.PostgresNoRECOracle.getUnoptimizedQueryCount(PostgresNoRECOracle.java:125)
--	at sqlancer.postgres.oracle.PostgresNoRECOracle.check(PostgresNoRECOracle.java:60)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--Caused by: org.postgresql.util.PSQLException: ERROR: canceling statement due to user request
--	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
--	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
--	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
--	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
--	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
--	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
--	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
--	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
--	at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:129)
--	... 10 more
---- Time: 2022/12/31 13:27:03
-- Database: database3
-- Database version: 14.6
-- seed value: 1672281630838
\c test;
DROP DATABASE IF EXISTS database3;
CREATE DATABASE database3  TEMPLATE template0;
\c database3;
CREATE TEMPORARY TABLE IF NOT EXISTS t0(c0 DECIMAL ) WITH (autovacuum_analyze_scale_factor=0.01, parallel_workers=879, fillfactor=70, autovacuum_vacuum_cost_limit=7601);
CREATE TABLE IF NOT EXISTS t1(c0 inet ) INHERITS(t0) PARTITION BY HASH((((chr((FALSE)::INT))||(CAST(0.2578964 AS MONEY))))) WITH (autovacuum_analyze_scale_factor=0.9, parallel_workers=73, autovacuum_analyze_threshold=1070764457, autovacuum_vacuum_cost_delay=36, autovacuum_freeze_min_age=86298167, autovacuum_freeze_table_age=279810749);
CREATE TEMP TABLE t1(LIKE t0);
CREATE TEMP TABLE IF NOT EXISTS t2(c0 inet ) ON COMMIT DELETE ROWS ;
CREATE UNLOGGED TABLE t3(c0 int4range , c1 BIT VARYING(499)  UNIQUE DEFAULT (((((((((B'11110010111011011001001011111')>>(B'11110010111011011001001011111')))#(((B'11110010111011011001001011111')|(B'11110010111011011001001011111')))))&(((((B'11110010111011011001001011111')||(B'1111111111111111111111111111111111010111100010101100001000011110')))>>(((B'1111111111111111111111111111111110011110101101011111101000010110')<<(B'10011111000111000111001111011')))))))#(((((((B'1111111111111111111111111111111110100110100001101110010101110110')>>(B'1111111111111111111111111111111111010111100010101100001000011110')))||(((B'1010111010101010110100110011101')&(B'1111111111111111111111111111111110001011110011111100100000101010')))))||(((((B'1111111111111111111111111111111111011110110100100010111000110101')>>(B'110011001101100101010010101')))>>(((B'1111111111111111111111111111111111010111100010101100001000011110')||(B'1111111111111111111111111111111110100110100001101110010101110110'))))))))) NULL) PARTITION BY HASH(('30.255.149.155')char_bloom_ops);
CREATE TEMPORARY TABLE t3(LIKE t0);
DROP INDEX IF EXISTS i0, i4, i2;
DROP INDEX IF EXISTS i0;
INSERT INTO t0(c0) VALUES(0.04151981999569887005208101982134394347667694091796875);
UPDATE t2 SET c0='66.254.144.157' WHERE NOT ((((NULL)|(B'1111111111111111111111111111111111010110001100101101000110101101'))) NOT IN (B'1111111111111111111111111111111110000101000010111000000100000011'));
INSERT INTO t1(c0) VALUES(0.79508980189719846709550665764254517853260040283203125), (0.2700773083196115198489906106260605156421661376953125), ((0.23802447232042856)::DECIMAL);
UPDATE t1 SET c0=DEFAULT WHERE TRUE;
INSERT INTO t3(c0) VALUES(0.812519580335715030372512046596966683864593505859375);
ALTER TABLE  t1 SET LOGGED, ADD CONSTRAINT o PRIMARY KEY(c0) WITH (autovacuum_freeze_max_age=439567769, autovacuum_vacuum_threshold=1813790608) NOT VALID, SET WITHOUT OIDS, NOT OF, REPLICA IDENTITY NOTHING, VALIDATE CONSTRAINT asdf, ALTER c0 DROP DEFAULT, OWNER TO SESSION_USER, ALTER c0  RESET(n_distinct_inherited, n_distinct), ALTER c0 SET STORAGE EXTERNAL, ALTER c0 SET NOT NULL, FORCE ROW LEVEL SECURITY, ALTER c0 SET STATISTICS 5265, NO FORCE ROW LEVEL SECURITY, ENABLE ROW LEVEL SECURITY;
ALTER TABLE  t2 NO FORCE ROW LEVEL SECURITY, ALTER c0 SET DEFAULT '3.105.247.165', FORCE ROW LEVEL SECURITY, ALTER c0 SET NOT NULL, OWNER TO CURRENT_USER, SET WITHOUT OIDS, ALTER c0  SET DATA TYPE VARCHAR(429) COLLATE "tsvector_ops", VALIDATE CONSTRAINT asdf, ALTER c0 SET STORAGE EXTENDED, ALTER c0  RESET(n_distinct_inherited, n_distinct), REPLICA IDENTITY NOTHING, DISABLE ROW LEVEL SECURITY, ADD CONSTRAINT 遆 EXCLUDE (c0 bool_ops NULLS FIRST WITH <<) WHERE ((t2.c0)::VARCHAR!~*(((to_ascii('4#') COLLATE "C"))||(((t2.c0)IS DISTINCT FROM('101.251.2.105'))))) NOT VALID, NOT OF, SET UNLOGGED;
TRUNCATE t2, t1, t3;
RESET ROLE;
UPDATE t2 SET c0='115.109.142.5' WHERE (t2.c0) BETWEEN SYMMETRIC (t2.c0) AND ('183.129.163.226');
INSERT INTO t1(c0) VALUES(0.81881943035243598405514831028995104134082794189453125), (0.45777153827678518371868676695157773792743682861328125), (0.08085635111351752168928896935540251433849334716796875);
UPDATE t1 SET c0=(t1.c0) WHERE ((- (((2023397145)+(1923450856))))::VARCHAR(454) SIMILAR TO ((((-1293874903)::VARCHAR(936))||(+ (258452828))) COLLATE "C"));
UPDATE t2 SET c0=DEFAULT WHERE (to_hex((('遆F')||(0.2578964))))::BOOLEAN;
UPDATE t2 SET c0='69.177.36.28' WHERE inet_same_family('30.118.237.25', '69.36.100.18');
RESET ALL;
INSERT INTO t2(c0) OVERRIDING USER VALUE VALUES('42.84.136.222');
CREATE UNIQUE INDEX i0 ON ONLY t0(c0) INCLUDE(c0) WHERE ((((t0.c0)=(t0.c0)))OR(CAST(((((B'1001110110100100011000001001100')#(B'1001011100110001000011001011100')))>>(((B'1111111111111111111111111111111110110111111111101001010110000000')#(B'1111111111111111111111111111111111110001100001000010000000011110')))) AS BOOLEAN)));
CREATE UNIQUE INDEX i0 ON t2 USING GIN((((((((((B'1100010001101001011110011010000')>>(B'1110010010101100101110010111000')))<<(((B'1000100001101001111111010101101')>>(B'1111010101010000011000100111010')))))<<(((((B'1000100001101001111111010101101')||(B'1001001100011001101101111101')))|(((B'1111111111111111111111111111111110101100000110100000011101110011')#(NULL)))))))>>(((((((B'1011101101110111001001011100110')|(B'1111111111111111111111111111111111000101001001111011100111011010')))||(((B'1110101010000011000010010110111')#(B'1011011101111000111011010011011')))))<<(((((B'1111111111111111111111111111111111110001011101000111101100010011')#(B'111011100010011100100100100000')))|(((B'10011001111001100000010110000')<<(B'1101100010011011110110101010'))))))))) timestamp_bloom_ops ASC) INCLUDE(c0) WHERE CAST('19.171.144.86' AS BOOLEAN);
CREATE UNIQUE INDEX i0 ON ONLY t3((CAST(0.06290453 AS MONEY)), (range_merge((((((('[-1445620627,-819718273)'::int4range)+('[-1897933744,1428812648]'::int4range)))*((('[978828203,1268287068)'::int4range)*('(-933529040,1071014832)'::int4range)))))*((((('[-933529040,24960755]'::int4range)+('[817413813,843113499)'::int4range)))+((('[-1897933744,-856765058]'::int4range)*('[-756241844,-63538097)'::int4range)))))), (((((('(-1878278317,-1448572344]'::int4range)-('[-9223372036854775808,16830337]'::int4range)))+((('[-965861697,2064621070)'::int4range)*('[-417693090,1370312374)'::int4range)))))-((((('(802665609,1370312374)'::int4range)-('(325051529,575794798]'::int4range)))+(CAST(TRUE AS int4range))))))) DESC) INCLUDE(c0) WHERE pg_is_other_temp_schema();
CREATE UNIQUE INDEX i0 ON t2 USING HASH(c0);
CREATE UNIQUE INDEX i0 ON t3(c0 ASC, (0.33381567127682465478955009530181996524333953857421875) int4_minmax_multi_ops DESC);
CREATE INDEX i0 ON ONLY t0(c0, (ascii((t0.c0)::VARCHAR(12))) ASC) INCLUDE(c0);
DISCARD SEQUENCES;
UPDATE t1 SET c0=0.8639695362907728881651792107732035219669342041015625 WHERE upper_inf((((((('(-1433901696,-1404619032]'::int4range)+('(-1236300802,-1088384535)'::int4range)))*((('[-987252262,-4715877)'::int4range)-('[509456991,1191892360)'::int4range)))))+(((('(\nW')::int4range)+((('(-1545294044,389762677]'::int4range)*('[1266016807,9223372036854775807)'::int4range)))))));
UPDATE t0 SET c0=0.89856822220590182315191896122996695339679718017578125 WHERE ((((((('[-819718273,-221073643)'::int4range)*('(741454314,1981184517]'::int4range)))+((('(-1236300802,197682651)'::int4range)*('[-1722088893,-261550192)'::int4range)))))::VARCHAR)LIKE('d<咞-'));
INSERT INTO t0(c0) VALUES(0.11062753804741809471323676916654221713542938232421875), (0.59863735940167062121730623402982018887996673583984375), (0.5300914429401710759037769093993119895458221435546875);
INSERT INTO t3(c0) VALUES(0.2757877411532108080649550174712203443050384521484375);
SET CONSTRAINTS ALL IMMEDIATE;
INSERT INTO t1(c0) VALUES(0.94811775379910911976111265175859443843364715576171875);
INSERT INTO t2(c0) VALUES('85.69.109.36'), ('111.171.163.254'), ('150.253.125.86');
INSERT INTO t1(c0) VALUES(0.8881048505527082692623253024066798388957977294921875);
REINDEX DATABASE CONCURRENTLY database3;
INSERT INTO t1(c0) VALUES(0.8275026957644764369348422405892051756381988525390625);
CREATE TEMPORARY VIEW v0(c0, c1, c2) AS (SELECT DISTINCT ON ('210.251.9.199') t0.c0, '247.222.162.62', ((+ (((length('WX<'))-(+ (-1293874903)))))+(+ ((((B'1001001101011101000001100011101')||(B'101111010011100000110011100')))::INT))) FROM t0* WHERE ((t0.c0)<(t0.c0))) WITH CASCADED CHECK OPTION;
INSERT INTO t2(c0) VALUES('155.210.222.182'), ('36.74.148.144'), ('87.100.72.209');
DELETE FROM t0 WHERE (left(abs(197682651), '}y') SIMILAR TO (((upper('1965598236'))||((t0.c0) BETWEEN SYMMETRIC (t0.c0) AND (t0.c0))) COLLATE "C")) RETURNING ((((((((B'1110011001010110110011000100')#(B'1111111111111111111111111111111110101100000110100000011101110011')))>>(((B'1000000000000000000000000000000000000000000000000000000000000000')|(B'110010001001010010001000101')))))&(((((B'1111111111111111111111111111111110101110101000000101111101110000')||(B'1111111111111111111111111111111111010100110100111000100001010011')))||(((B'1111010010010100000000000110101')|(B'1111111111111111111111111111111110001100011001001111001000111101')))))))>>((((t0.c0)::BIT)&(((((B'111101110101001011110001011010')||(B'1111111111111111111111111111111110101111100011000000101101000101')))||(((B'1111111111111111111111111111111110110110010011111000101111111110')<<(NULL))))))));
DELETE FROM t3;
DISCARD SEQUENCES;
INSERT INTO t2(c0) VALUES('73.27.142.42');
INSERT INTO t2(c0) VALUES('74.218.101.102'), ('144.102.109.4'), ('32.46.136.0');
UPDATE t1 SET c0=0.18216920397525682151496084770769812166690826416015625 WHERE lower_inc(CAST(broadcast('164.46.116.74') AS int4range));
UPDATE t2 SET c0='13.19.237.230' WHERE NOT (NOT (((('ࠀ' SIMILAR TO '644933651'))OR((('?)-P^1I')LIKE('K'))))));
DISCARD PLANS;
REINDEX TABLE t3;
INSERT INTO t0(c0) VALUES(0.96219771658996167129629384362488053739070892333984375);
INSERT INTO t1(c0) VALUES(0.45354444124359627465992161887697875499725341796875), (0.2788908701610302021123288795934058725833892822265625), (0.18249476779856610431096441971021704375743865966796875);
INSERT INTO t1(c0) VALUES(0.3245179132601314631045852365787141025066375732421875);
INSERT INTO t2(c0) VALUES('14.124.72.55'), ('75.219.77.192'), ('120.137.155.147');
INSERT INTO t0(c0) VALUES(0.6267071776191699417069003175129182636737823486328125);
DISCARD SEQUENCES;
INSERT INTO t0(c0) VALUES(0.46544271067257281249140987711143679916858673095703125);
DROP INDEX IF EXISTS i0 CASCADE;
UPDATE t3 SET c0=0.72977826505300125159436674948665313422679901123046875 WHERE ((((('F*1')||('196.9.70.177')) COLLATE "C") SIMILAR TO convert_from('Rr1G>pڟ*', 'UTF8'))) IS TRUE;
UPDATE t2 SET c0=DEFAULT WHERE (('32.36.55.101')<(t2.c0));
INSERT INTO t1(c0) VALUES(0.851115496545920446891386745846830308437347412109375), (0.02359142700806338144303708759252913296222686767578125), (0.2866126594807434369016618802561424672603607177734375);
INSERT INTO t1(c0) VALUES(0.128137530791351483827611446031369268894195556640625);
DELETE FROM ONLY t3 RETURNING (((- (CAST(1368053533 AS INT)))*(- (strpos('', '')))))::DECIMAL;
INSERT INTO t1(c0) VALUES(0.08723700868141193165428148859064094722270965576171875), (0.758307839435560904206568011431954801082611083984375), (0.316055447466806693768148761591874063014984130859375);
DROP INDEX IF EXISTS i0 CASCADE;
SET enable_parallel_append=1;
CREATE INDEX i0 ON t3 USING HASH(c0) WHERE lower_inc('[1,1965598236]'::int4range);
INSERT INTO t2(c0) VALUES('142.109.91.17') ON CONFLICT (c0) DO NOTHING;
INSERT INTO t1(c0) VALUES(0.73865622326092694738264299303409643471240997314453125);
INSERT INTO t0(c0) VALUES(0.138320294332356041877574170939624309539794921875), (0.00465506658632108827333695444394834339618682861328125), (0.5893218309830035028795691687264479696750640869140625);
COMMIT;
SET SESSION statement_timeout = 5000;\n;
```

**Comment by mrigger** [comment]
In the case where SQLancer prints only a single `SELECT` and an exception, SQLancer believes to have found an internal error (which is "ERROR: canceling statement due to user request" in this case). This might perhaps be due to an unexpected/unsupported Postgres version. If this error might be expected for the version you are testing, you can ignore it by adding an entry to the `ExpectedErrors` object: https://github.com/sqlancer/sqlancer/blob/7f1efbd4ba672f387ea2034b07bcbaf3b23e69d2/src/sqlancer/postgres/oracle/PostgresNoRECOracle.java#L46

Like this, you only need to inspect log files that should indicate real bugs. Please let me know if this answers both of your questions.

**Comment by mozz85** [comment]
Thanks for your help, really do.
If i got this right, i should move to the log file which logged two SELECT.
and maybe move to pg 12 :)
