### ISSUE TITLE
[Java 8] Cannot start sqlancer on CentOS 8.1

### ISSUE THREAD

**Issue by ligurio** [sqlancer/sqlancer#7]
`CentOS Linux release 8.1.1911`

```
openjdk version "1.8.0_252"                                                                                                                       
OpenJDK Runtime Environment (build 1.8.0_252-b09)                                                                                                 
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

```
$ sudo java -jar SQLancer-0.0.1-SNAPSHOT.jar --num_threads 16 --num_tries 5 --max_expression_depth 3 --num_queries 100000 --max_num_inserts 30 sqlite3 --oracle query_partitioning                                                                     
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: sqlancer/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
$ 
```

**Comment by mrigger** [comment]
Thanks for the report! As stated in https://github.com/sqlancer/sqlancer#getting-started, SQLancer assumes a Java 11 JDK. I will investigate if it's feasible to lower the version to Java 8.

**Comment by mrigger** [comment]
We've added support for Java 8, which we now also test in our CI, see https://github.com/sqlancer/sqlancer/pull/62.
