### ISSUE TITLE
Yugabyte crash bug?

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#711]
The Yugatebyte CI tests occasionally fail such as shown below.

```
--java.lang.AssertionError: SELECT ((true)OR(false)) FROM t0;
--	at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:109)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:93)
--	at sqlancer.Main$QueryManager.execute(Main.java:265)
--	at sqlancer.GlobalState.executeStatement(GlobalState.java:108)
--	at sqlancer.yugabyte.ycql.test.YCQLFuzzer.check(YCQLFuzzer.java:40)
--	at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:364)
--	at sqlancer.Main$2.run(Main.java:559)
--	at sqlancer.Main$2.runThread(Main.java:541)
--	at sqlancer.Main$2.run(Main.java:532)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:829)
--Caused by: java.sql.SQLTransientException: com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer
--	at com.ing.data.cassandra.jdbc.CassandraStatement.doExecute(CassandraStatement.java:339)
--	at com.ing.data.cassandra.jdbc.CassandraStatement.execute(CassandraStatement.java:346)
--	at sqlancer.common.query.SQLQueryAdapter.execute(SQLQueryAdapter.java:87)
--	... 11 more
--Caused by: com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer
--	at com.datastax.oss.driver.api.core.connection.ClosedConnectionException.copy(ClosedConnectionException.java:51)
--	at com.datastax.oss.driver.internal.core.util.concurrent.CompletableFutures.getUninterruptibly(CompletableFutures.java:149)
--	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:53)
--	at com.datastax.oss.driver.internal.core.cql.CqlRequestSyncProcessor.process(CqlRequestSyncProcessor.java:30)
--	at com.datastax.oss.driver.internal.core.session.DefaultSession.execute(DefaultSession.java:230)
--	at com.datastax.oss.driver.api.core.cql.SyncCqlSession.execute(SyncCqlSession.java:54)
--	at com.ing.data.cassandra.jdbc.CassandraStatement.doExecute(CassandraStatement.java:333)
--	... 13 more
--
```

Subsequently, many "Invalid keyspace" errors are printed. I suspect that this might be a crash bug in Yugabyte? @qvad do you want to report this issue and/or have time to look into this?

**Comment by ZhengLin-Li** [comment]
@mrigger it seams this is no longer a problem. how about close this issue?

**Comment by mrigger** [comment]
Sounds good!
