### ISSUE TITLE
PostgreSql - java.lang.AssertionError related to lack of permissions for pg_current_logfile

### ISSUE THREAD

**Issue by TrickyDoodle** [sqlancer/sqlancer#725]
I've tried to use sqlancer v2.0.0 with PostgreSql 12 / 14 with default user "sqlancer". After test launching I encountered errors such as: 

``` 
java.lang.AssertionError: SELECT SUM(count) FROM (SELECT ALL CAST(((((((((((('(-576685446,1408015908)'::int4range)-('(-387585479,1907211990]'::int4range)))@>((('[271275617,855266584)'::int4range)+('[-1691594921,506475461]'::int4range)))))::BOOLEAN)OR(((t3.c0)LIKE(t1.c0)))))AND(((pg_current_logfile())LIKE(t3.c0)))))OR((t5.c0) BETWEEN SYMMETRIC (t5.c0) AND (t5.c0))) AS INT) as count FROM ONLY t1, ONLY t4, ONLY t3 FULL OUTER JOIN ONLY t5 ON TRUE LEFT OUTER JOIN t0 ON ((t3.c0 COLLATE "en_DK.utf8") SIMILAR TO t5.c2)) as res;
            at sqlancer.common.query.SQLQueryAdapter.checkException(SQLQueryAdapter.java:109)
            at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:139)
            at sqlancer.postgres.oracle.PostgresNoRECOracle.getUnoptimizedQueryCount(PostgresNoRECOracle.java:125)
            at sqlancer.postgres.oracle.PostgresNoRECOracle.check(PostgresNoRECOracle.java:60)
            at sqlancer.ProviderAdapter.generateAndTestDatabase(ProviderAdapter.java:61)
            at sqlancer.Main$DBMSExecutor.run(Main.java:364)
            at sqlancer.Main$2.run(Main.java:559)
            at sqlancer.Main$2.runThread(Main.java:541)
            at sqlancer.Main$2.run(Main.java:532)
            at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
            at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
            at java.base/java.lang.Thread.run(Thread.java:829)
    Caused by: org.postgresql.util.PSQLException: ERROR: permission denied for function pg_current_logfile
            at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
            at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
            at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
            at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
            at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
            at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
            at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
            at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
            at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:244)
            at sqlancer.common.query.SQLQueryAdapter.executeAndGet(SQLQueryAdapter.java:129)
            ... 10 more
```

In addition new databases creates from template0:

```
\c test;
DROP DATABASE IF EXISTS database75;
CREATE DATABASE database75 WITH ENCODING 'utf8'  TEMPLATE template0;
\c database75;
```

AFAIK we should use template1 for database creation - see details in https://www.postgresql.org/docs/current/manage-ag-templatedbs.html

I fixed errors above with the following: 

1) Changed template in src/sqlancer/postgres/PostgresProvider.java
2) Built project with a new value
3) Performed db commands:

```
\c template1 postgres
GRANT EXECUTE ON FUNCTION pg_catalog.pg_current_logfile() TO sqlancer;
```

After that the errors are gone.

I just want to understand am I on the right way and there is a bug in a configuration or may be I missed smth.  

BR.

**Comment by mrigger** [comment]
It seems the reason for the error seems to be insufficient permissions, which was solved with the `GRANT` command? Typically, when running SQLancer, I give it `SUPERUSER` permissions to test all kinds of features.

We use `TEMPLATE template0` only with some probability, so that we can also test this feature (see https://github.com/sqlancer/sqlancer/blob/40a1d26adaa0cc76050aa9380d271565862e4f95/src/sqlancer/postgres/PostgresProvider.java#L339).

Not sure if this answered your questions?
