### ISSUE TITLE
Program always throw Deadlock when testing mysql

### ISSUE THREAD

**Issue by BlockFuzz** [sqlancer/sqlancer#732]
SQLancer constantly throws Deadlock exception, cannot tests mysql correctly.
The error info is:
```
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Deadlock found when trying to get lock; try restarting transaction
  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:123)
  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
  at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:763)
  at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
  at sqlancer.mysql.MySQLProvider.createDatabase(MySQLProvider.java:175)
  at sqlancer.mysql.MySQLProvider.createDatabase(MySQLProvider.java:1)
  at sqlancer.Main$DBMSExecutor.run(Main.java:347)
  at sqlancer.Main$2.run(Main.java:559)
  at sqlancer.Main$2.runThread(Main.java:541)
  at sqlancer.Main$2.run(Main.java:532)
  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
  at java.base/java.lang.Thread.run(Thread.java:829)

```
The SQLancer setup command is:
```
java -jar sqlancer-2.0.0.jar --num-tries 10000000 --username=xxx --password=xxx mysql
```
My testing environment is Ubuntu 22.04

**Comment by vivektangudu123** [comment]
it's working fine

**Comment by mrigger** [comment]
Which MySQL version are you using? See https://github.com/sqlancer/sqlancer#i-am-running-sqlancer-on-the-latest-version-of-a-supported-dbms-is-it-expected-that-sqlancer-prints-many-assertionerrors for a potential cause of this exception.

**Comment by mrigger** [comment]
Closing this due to inactivity. Feel free to re-open the issue in case the answer above did not address the issue.
