### ISSUE TITLE
Sqlancer dosen't support postgresql?

### ISSUE THREAD

**Issue by Doris404** [sqlancer/sqlancer#832]
`java -jar sqlancer-*.jar --num-threads 4 pgsql --oracle NoREC`  fail, and return following error:
```
Exception in thread "main" com.beust.jcommander.MissingCommandException: Expected a command, got sqlite
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:795)
        at com.beust.jcommander.JCommander.parse(JCommander.java:363)
        at com.beust.jcommander.JCommander.parse(JCommander.java:342)
        at sqlancer.Main.executeMain(Main.java:490)
        at sqlancer.Main.main(Main.java:319)
```

I have already installed postgresql 10.23 on Ubuntu 18.04.2, and `/sqlancer/target$ java -jar sqlancer-*.jar --num-threads 4 sqlite3 --oracle NoREC` success. I am wondering how to run sqlancer on postgresql. A lot of thanks for help.

**Comment by oraluben** [comment]
use `postgres` in the command: `java -jar sqlancer-*.jar --num-threads 4 postgres --oracle NoREC`. Other parameter such as database connect arguments may be also needed.
