### ISSUE TITLE
Sqlancer dosen't support Mysql?

### ISSUE THREAD

**Issue by Doris404** [sqlancer/sqlancer#833]
`java -jar sqlancer-*.jar --num-threads 4 mysql -u debian-sys-maint -p NpJPdPOfUpoIj8B8 --oracle PQS` fail, and return 
```
Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter '-u' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:961)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:762)
        at com.beust.jcommander.JCommander.parse(JCommander.java:363)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:803)
        at com.beust.jcommander.JCommander.parse(JCommander.java:363)
        at com.beust.jcommander.JCommander.parse(JCommander.java:342)
        at sqlancer.Main.executeMain(Main.java:490)
        at sqlancer.Main.main(Main.java:319)
```

I have already installed mysql 5.7.42 on Ubuntu18.04.1. `java -jar sqlancer-*.jar --num-threads 4 sqlite3 --oracle NoREC` success. A lot of thanks for help.

**Comment by oraluben** [comment]
sqlancer does not follow mysql's `-u` and `-p` for username and password. Use `--username` and `--password`.
If not given, sqlancer uses `sqlancer` as both username and password.
