### ISSUE TITLE
Meaningful error message when connection fails

### ISSUE THREAD

**Issue by mrigger** [sqlancer/sqlancer#92]
When SQLancer cannot connect to the DBMS under test, it currently repeatedly fails while printing an output such as the following:

```
--com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
--
--The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
--	at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174)
--	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64)
--	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:836)
--	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
--	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246)
--	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:197)
--	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
--	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
--	at sqlancer.mysql.MySQLProvider.createDatabase(MySQLProvider.java:243)
--	at sqlancer.mysql.MySQLProvider.createDatabase(MySQLProvider.java:1)
--	at sqlancer.Main$DBMSExecutor.run(Main.java:312)
--	at sqlancer.Main$1.runThread(Main.java:430)
--	at sqlancer.Main$1.run(Main.java:423)
--	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
--	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
--	at java.base/java.lang.Thread.run(Thread.java:834)
--Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
```

This might be confusing to users. It would be better to print an error message that SQLancer cannot connect, and refer to the relevant settings to set, for example, the user credentials.

**Comment by mrigger** [comment]
Addressed by https://github.com/sqlancer/sqlancer/pull/115.
